name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
#     - run: echo Hello ${{ inputs.who-to-greet }}.
#       shell: bash
    - name: Hello World!
      uses: guan-kevin/javascript-action@v5
      with:
        who-to-greet: 'guan-kevin'
    - name: Hello World Again!
      uses: guan-kevin/javascript-action@v7
      with:
        who-to-greet: 'guan-kevin'
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash
    - id: print-random-number-generator
      run: echo "Random number is $RANDOM"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
    - run: |
        echo "actor: ${{ github.actor }}"
        echo "ref: ${{ github.ref }}"
        echo "triggering_actor: ${{ github.triggering_actor }}"
        echo "workflow: ${{ github.workflow }}"
        echo "head_ref: ${{ github.head_ref }}"
        echo "base_ref: ${{ github.base_ref }}"
        echo "event_name: ${{ github.event_name }}"
        echo "action: ${{ github.action }}"
        echo "action_repository: ${{ github.action_repository }}"
        echo "action_ref: ${{ github.action_ref }}"
        echo "action_path: ${{ github.action_path }}"
        echo "action_status: ${{ github.action_status }}"
        echo "workspace: ${{ github.workspace }}"
      shell: bash
    - name: Python 3
      run: |
        import os
        print('Workflow: {} and Job: {} and Step: {} and Local: {}'.format(os.getenv('WorkflowEnv'), os.getenv('JobEnv'), os.getenv('StepEnv'), os.getenv('LocalEnv')))
        print('Workflow: {} and Job: {} and Step: {} and Local: {}'.format("${{ env.WorkflowEnv }}", "${{ env.JobEnv }}", "${{ env.StepEnv }}", "${{ env.LocalEnv }}"))
      shell: python
      env:
        LocalEnv: Local Step Level
    - run: pwd && ls
      shell: bash
